token:
  expiration_time: 86400000 #86400000 # 24시간
  secret:  c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK

gateway:
  ip: 175.116.181.23
 
value:
  check: prod # config refresh 확인용