server:
  port: 8888
spring:
  application:
    name: config-service
  #profiles:
  #  active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/selre1/ft-msa-service.git
          default-label: main
          search-paths: ft-repo
        #native:
        #  search-locations: file:/config #file:///${user.home}/Desktop/ft-repo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

encrypt:
  key: asdbdfkdrjieifjiejiewiosj12345678902456789